# Generated by Django 6.0.6 on 2026-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد نسخه'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='فارسی', max_length=50, verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, verbose_name='خلاصه کتاب'),
        ),
    ]
