# Generated by Django 6.0.6 on 2026-07-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_copies_book_language_book_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrow_date', models.DateField(verbose_name='تاریخ امانت')),
                ('due_date', models.DateField(verbose_name='تاریخ تحویل')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امانت',
                'verbose_name_plural': 'امانت\u200cها',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
