# Generated by Django 6.0.6 on 2026-07-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='edit_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت ویرایش'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد درخواست'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('returned', 'برگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست'),
        ),
    ]
