# Generated by Django 6.0.6 on 2026-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrow_approved_at_borrow_edit_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ امانت'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
