# Generated by Django 6.0.6 on 2026-07-04 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrow_borrow_date_alter_borrow_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ثبت درخواست'),
            preserve_default=False,
        ),
    ]
