# Generated by Django 6.0.6 on 2026-07-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_is_active_alter_borrow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='book_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان کتاب'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrows', to='books.book', verbose_name='کتاب'),
        ),
    ]
