# Generated by Django 6.0.6 on 2026-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.PositiveIntegerField(verbose_name='سال انتشار'),
        ),
    ]
