# Generated by Django 6.0.6 on 2026-07-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100, unique=True, verbose_name='ISBN'),
        ),
    ]
